### ISSUE TITLE
Script only respecting certain links

### ISSUE THREAD

**Issue by robobeirne** [fzakaria/HypeMachine-Extension#13] opened 2014-12-23 15:32 UTC
Seems that the script only appears to be working on 1/2 songs on Hype Machine any idea on why it doesn't respect and download all links? This is the Chrome fix FYI.

Thanks -

**Comment by AwhileGone** [comment] 2015-01-06 02:00
Having the same issue.  I've realized that the script to download is only working on about 1/2 the songs.  I cannot discern what the pattern is, but it's only begun happening in the last few weeks.  Save us Farid!!!

**Comment by fzakaria** [comment] 2015-01-06 22:13
Hey guys,
I'll try to look at this sometime this upcoming weekend.
If you could provide me with additional information:

- The songs that fail to download are deterministic ? (Always occur)
If so, please provide me one example song to use.

**Comment by AwhileGone** [comment] 2015-01-07 03:13
3 example songs that deterministically refuse to download:

Keys N Krates - Are We Faded
Sister Nancy - Bam Bam Top Billin Party Mix
Sister Nancy - Bam Bam

Let me know if I can help you by providing any additional information.
Thanks Farid!

**Comment by fzakaria** [comment] 2015-01-09 14:43
Here is some investigation:
```
 XMLHttpRequest cannot load https://cf-media.sndcdn.com/DHD78pQp69gh.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt…uwrxaktcpuU4~Me0R7VtUip1pyWW43Sz2I73IbA__&Key-Pair-Id=APKAJAGZ7VMH2PFPW6UQ. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.
```

**Comment by fzakaria** [comment] 2015-01-09 15:04
Looks like this can't be resolved: http://stackoverflow.com/questions/15099895/soundcloud-cors 

Relevant: Unfortunately, at the moment, the CORS headers aren't enabled on the mp3 files that are delivered from the CDN (ec-media subdomain). You'd need to use a proxy if you need to request these files via XHR.

CORS headers are enabled on the JSON data returned from the API, but not the mp3s.

If you are trying to use Web Audio API you could use mediaElementSource and load the mp3 via setting src property of the audio to be used as “media source” as described here.

**Comment by robobeirne** [comment] 2015-02-23 14:27
So do you reckon this is a dead issue?

**Comment by fzakaria** [comment] 2015-02-23 17:07
I think you can try to send soundcloud an email asking them to enable CORS.
It sounds like a dead issue for a simple extension without anything more involved (going through a proxy)

**Comment by fzakaria** [comment] 2015-02-23 17:08
I'm closing the ticket.

**Closed by fzakaria** 2015-02-23 17:08 UTC

**Comment by sgralph** [comment] 2015-03-04 04:36
I've found that you can still save all tracks by right clicking the download button and selecting "save link as..." although the track names are lost. This works despite a track not downloading if the button is clicked normally.

**Comment by AwhileGone** [comment] 2015-03-04 11:55
Oh my gosh, Sgralph you are my hero!

**Comment by AwhileGone** [comment] 2015-03-04 11:56
Confirmed works, now just gotta get on top of this backlog.... Cheers man!

**Comment by robobeirne** [comment] 2015-03-06 13:41
Yeah the only issue that I do this in bulk so it's hard to track what didn't actually work and sometimes the effort of changing the track name isn't worth the effort of downloading it if there's loads of files. Thanks for looking into it though.
